server:
  port: 8086
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: liming
    password: liming
    virtual-host: /liming
    listener:
      simple:
        acknowledge-mode: manual #手动签收
        prefetch: 1 #每次从队列中取一个,轮询分发，默认是公平分发
        retry:
          max-attempts: 1 #重试次数
          enabled: true #开启重试