server:
  port: 8088
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: liming
    password: liming
    virtual-host: /liming
    publisher-confirm-type: correlated  # 必须开启确认机制
    publisher-returns: true